services:
 bind9:
  container_name: container-name
  image: ubuntu/bind9:latest
  environment:
   - BIND9_USER=root
   - TZ=live-zone
  ports:
   - "53:53/tcp" # Bind9 a besoin que ce port soit ouvert pour les diverses recherche
   - "53:53/udp"
  volumes:
   - ./config:/etc/bind # Fichier de configuration avec les zones
   - ./cache:/var/cache/bind # Cache DNS
   - ./records:/var/lib/bind
  restart: unless-stopped
